version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data

  payment-recommendation-server:
    build:
      context: ./apps/smart-routing
      dockerfile: Dockerfile
    container_name: payment-recommendation-server
    restart: always
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data:ro

  voice-auth-server:
    build:
      context: ./apps/voice-auth
      dockerfile: Dockerfile
    container_name: voice-auth-server
    restart: always
    env_file:
      - .env
    ports:
      - "3533:3533"
    volumes:
      - ./data:/app/data
